// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaFotografa;

namespace SistemaFotografa.Presentation.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190520131904_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaFotografa.DomainModel.Entities.Album", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("ClienteId");

                    b.Property<string>("Descricao");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Album");
                });

            modelBuilder.Entity("SistemaFotografa.DomainModel.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("LoginUsername");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("LoginUsername");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("SistemaFotografa.DomainModel.Entities.Foto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AlbumId");

                    b.Property<string>("Descricao");

                    b.Property<byte[]>("Imagem");

                    b.Property<string>("Nome");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("Foto");
                });

            modelBuilder.Entity("SistemaFotografa.DomainModel.ValueObjects.Login", b =>
                {
                    b.Property<string>("Username")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Password");

                    b.HasKey("Username");

                    b.ToTable("Login");
                });

            modelBuilder.Entity("SistemaFotografa.DomainModel.Entities.Album", b =>
                {
                    b.HasOne("SistemaFotografa.DomainModel.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId");
                });

            modelBuilder.Entity("SistemaFotografa.DomainModel.Entities.Cliente", b =>
                {
                    b.HasOne("SistemaFotografa.DomainModel.ValueObjects.Login", "Login")
                        .WithMany()
                        .HasForeignKey("LoginUsername");
                });

            modelBuilder.Entity("SistemaFotografa.DomainModel.Entities.Foto", b =>
                {
                    b.HasOne("SistemaFotografa.DomainModel.Entities.Album")
                        .WithMany("Fotos")
                        .HasForeignKey("AlbumId");
                });
#pragma warning restore 612, 618
        }
    }
}
